---
- name: initialize RPi after a fresh Raspbian flash
  hosts: all
  vars_files:
  - ./params.yml
  remote_user: "{{ default_user }}"
  become: yes
  roles:
     - raspbian-init
#     - blalop.pihole
