---
- name: initialize RPi after a fresh Raspbian flash
  hosts: rpis
  vars_files:
  - ./params.yml
  remote_user: "{{ default_user }}"
  become: yes
  tasks:
    - roles:
        - raspbian-init
        - blalop.pihole
